var vega = "chart.json";
var vega2 = "chart2.json";
var vega3 = "chart3.json";
var vega4 = "chart4.json";
var vega5 = "chart5.json";
var vega6 = "chart6.json";
var vega7 = "chart7.json";
var vega8 = "chart8.json";
vegaEmbed("#Chart", vega);
vegaEmbed("#Chart2", vega2);
vegaEmbed("#Chart3", vega3);
vegaEmbed("#Chart4", vega4);
vegaEmbed("#Chart5", vega5);
vegaEmbed("#Chart6", vega6);
vegaEmbed("#Chart7", vega7);
vegaEmbed("#Chart8", vega8);
